name: Release Java CI

on:
  push:
    tags:
      - "*.*.*.rsp"
      - "*.*.*.rsp-*"
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set Version
        run: |
          mvn versions:set -DnewVersion=${{env.RELEASE_VERSION}}
          cat pom.xml
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}